### ISSUE TITLE
client [system] can't work with pm2

### ISSUE THREAD

**Issue by FlandreDaisuki** [FlandreDaisuki/dmhy-subscribe#11]
As title.

env
---
Linux Mint 18.3(Ubuntu 16.04)

$ dmhy -V
0.5.5
$ pm2 --version
2.10.1
$ node -v
v9.8.0
$ npm -v
5.6.0

**Comment by maple3142** [comment]
你是指像下面這樣的 error 嗎?
```
2|cli      | Error: Cannot find module '/usr/lib/node_modules/dmhy-subscribe/dl'
2|cli      |     at Function.Module._resolveFilename (module.js:555:15)
2|cli      |     at Function.Module._load (module.js:482:25)
2|cli      |     at Function.Module.runMain (module.js:701:10)
2|cli      |     at startup (bootstrap_node.js:194:16)
2|cli      |     at bootstrap_node.js:618:3
```

**Comment by FlandreDaisuki** [comment]
其實是因為我用正常 dl 可以 work
但 pm2 什麼 error msg 都沒噴給我QQ
回家再看看你的 PR, thx
